### ISSUE TITLE
Compile error `cargo bench`

### ISSUE THREAD

**Issue by mark-moir** [sam-jaques/allosaurust#2]
Hello

I tried running `cargo bench` using `cargo` version `1.75.0` and got a bunch of errors, for example:

```
error[E0599]: no method named `to_bytes` found for struct `G1Projective` in the current scope
   --> accumulator/src/proof.rs:595:76
    |
595 |         transcript.append_message(b"R_delta_sigma", self.cap_r_delta_sigma.to_bytes().as_ref());
    |                                                                            ^^^^^^^^ method not found in `G1Projective`
```
Any suggestions?  Thanks.

**Comment by sam-jaques** [comment]
Looks like one of the libraries installs now as v0.5.5 instead of v0.5.2; supposedly this should be backwards-compatible, but it wasn't. I updated the code and hopefully it fixes this.

**Comment by mark-moir** [comment]
Yes, great, thanks for the quick response!
